### ISSUE TITLE
Specializer doesn't work correct for the expression on JDK1.8, it throw Bad local variable type exception.

### ISSUE THREAD

**Issue by michaelmao999** [activej/activej#247]
I try to use ActiveJ Specializer optimize an expression engine liked your example, but the exception was thrown.

JDK 1.8
======================================================================
java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    com/zov/expression/function/SpecializedClass_1.MulDivModBinaryExpression$eval(Lcom/zov/common/model/entity/StandardEntityModel;)Ljava/lang/Object; @335: aload_2
  Reason:
    Type top (current frame, locals[2]) is not assignable to reference type
  Current Frame:
    bci: @335
    flags: { }
    locals: { 'com/zov/common/model/entity/StandardEntityModel' }
    stack: { }
  Bytecode:
    0x0000000: b200 2b59 b200 2ba6 000a 57b2 003e a700
    0x0000010: 09c0 0029 b400 e1c6 001e b200 2b59 b200
    0x0000020: 2ba6 000a 57b2 003e a700 09c0 0029 b400
    0x0000030: e14c a700 73b2 002b 59b2 002b a600 0a57
    0x0000040: b200 44a7 0009 c000 29b4 00f2 c600 26b2
    0x0000050: 002b 59b2 002b a600 0a57 b200 44a7 0009
    0x0000060: c000 29b4 00f2 c000 42b9 0146 0100 4da7
    0x0000070: 0036 b200 2b59 b200 2ba6 000a 57b2 0038
    0x0000080: a700 09c0 0029 b400 ad2a 4e59 b200 2ba6
    0x0000090: 000b 572d b801 48a7 000c c000 082d b901
    0x00000a0: 4b02 003a 04b2 002b 59b2 002b a600 0a57
    0x00000b0: b200 40a7 0009 c000 29b4 00e4 c600 1fb2
    0x00000c0: 002b 59b2 002b a600 0a57 b200 40a7 0009
    0x00000d0: c000 29b4 00e4 3a05 a700 77b2 002b 59b2
    0x00000e0: 002b a600 0a57 b200 46a7 0009 c000 29b4
    0x00000f0: 00f5 c600 27b2 002b 59b2 002b a600 0a57
    0x0000100: b200 46a7 0009 c000 29b4 00f5 c000 42b9
    0x0000110: 0146 0100 3a06 a700 39b2 002b 59b2 002b
    0x0000120: a600 0a57 b200 3aa7 0009 c000 29b4 00c8
    0x0000130: 2a3a 0759 b200 2ba6 000c 5719 07b8 0148
    0x0000140: a700 0dc0 0008 1907 b901 4b02 003a 082c
    0x0000150: c100 4899 0036 b201 4e2c c000 483a 09c0
    0x0000160: 002d 1909 b601 52c0 0154 b601 5899 001c
    0x0000170: b200 2b2c c000 483a 0a57 190a b801 5b3a
    0x0000180: 0b19 0bc6 0006 190b 4d19 06c1 0048 9900
    0x0000190: 39b2 014e 1906 c000 483a 0cc0 002d 190c
    0x00001a0: b601 52c0 0154 b601 5899 001e b200 2b19
    0x00001b0: 06c0 0048 3a0d 5719 0db8 015b 3a0e 190e
    0x00001c0: c600 0719 0e3a 06b2 002b 59b2 002b a600
    0x00001d0: 0a57 b200 54a7 0009 c000 29b4 0116 04a0
    0x00001e0: 0016 b200 2b2c 1906 3a0f 3a10 5719 1019
    0x00001f0: 0fb8 015e b0b2 002b 59b2 002b a600 0a57
    0x0000200: b200 54a7 0009 c000 29b4 0116 05a0 0016
    0x0000210: b200 2b2c 1906 3a11 3a12 5719 1219 11b8
    0x0000220: 0160 b0b2 002b 59b2 002b a600 0a57 b200
    0x0000230: 54a7 0009 c000 29b4 0116 06a0 0016 b200
    0x0000240: 2b2c 1906 3a13 3a14 5719 1419 13b8 0163
    0x0000250: b001 b0                                
  Stackmap Table:
    same_locals_1_stack_item_frame(@17,Object[#41])
    same_locals_1_stack_item_frame(@23,Object[#60])
    same_locals_1_stack_item_frame(@43,Object[#41])
    same_locals_1_stack_item_frame(@49,Object[#60])
    same_frame(@53)
    same_locals_1_stack_item_frame(@70,Object[#41])
    same_locals_1_stack_item_frame(@76,Object[#66])
    same_locals_1_stack_item_frame(@96,Object[#41])
    same_locals_1_stack_item_frame(@102,Object[#66])
    same_frame(@114)
    same_locals_1_stack_item_frame(@131,Object[#41])
    same_locals_1_stack_item_frame(@137,Object[#8])
    full_frame(@154,{Object[#357],Top,Top,Object[#357]},{Object[#8]})
    same_locals_1_stack_item_frame(@163,Object[#4])
    chop_frame(@165,3)
    same_locals_1_stack_item_frame(@182,Object[#41])
    same_locals_1_stack_item_frame(@188,Object[#60])
    same_locals_1_stack_item_frame(@208,Object[#41])
    same_locals_1_stack_item_frame(@214,Object[#60])
    same_frame(@219)
    same_locals_1_stack_item_frame(@236,Object[#41])
    same_locals_1_stack_item_frame(@242,Object[#66])
    same_locals_1_stack_item_frame(@262,Object[#41])
    same_locals_1_stack_item_frame(@268,Object[#66])
    same_frame(@281)
    same_locals_1_stack_item_frame(@298,Object[#41])
    same_locals_1_stack_item_frame(@304,Object[#8])
    full_frame(@323,{Object[#357],Top,Top,Top,Top,Top,Top,Object[#357]},{Object[#8]})
    same_locals_1_stack_item_frame(@333,Object[#4])
    full_frame(@335,{Object[#357]},{})
    same_frame(@393)
    same_frame(@455)
    same_locals_1_stack_item_frame(@472,Object[#41])
    same_locals_1_stack_item_frame(@478,Integer)
    same_frame(@501)
    same_locals_1_stack_item_frame(@518,Object[#41])
    same_locals_1_stack_item_frame(@524,Integer)
    same_frame(@547)
    same_locals_1_stack_item_frame(@564,Object[#41])
    same_locals_1_stack_item_frame(@570,Integer)
    same_frame(@593)

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at io.activej.specializer.Specializer$Specialization.ensureInstance(Specializer.java:161)
	at io.activej.specializer.Specializer.specialize(Specializer.java:806)
	at com.zov.expression.function.JSScriptEngineTest.runByOptimizedExpression(JSScriptEngineTest.java:69)
	at com.zov.expression.function.JSScriptEngineTest.performanceTest(JSScriptEngineTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

**Comment by eduard-vasinskyi** [comment]
Hi, @michaelmao999

Could you please provide a unit test or share a demo project that demonstrates the problem?

**Comment by michaelmao999** [comment]
[testCase.zip](https://github.com/activej/activej/files/10049089/testCase.zip)

**Comment by eduard-vasinskyi** [comment]
Thank you for the test case. We can confirm that there is currently a bug in a Specializer. We are looking for the best solution to fix it. I will let you know once it is fixed.

**Comment by eduard-vasinskyi** [comment]
@michaelmao999 

We have fixed the issue regarding incorrect local variable type. It is fixed in `master` branch commit 6c7dd7e9.

The fix will be part of an ActiveJ v5.5 release. For now, you can install ActiveJ locally from `master` branch (by running `sh ./install.sh` from project root). After that you can use 'ActiveJ ver. 5.5-SNAPSHOT' as a local dependency.

**Comment by michaelmao999** [comment]
The issue still exists, I create new case 256 attached new test code
